'use strict';

const path = require('path');

// Global variables
const EXECUTION_PATH = process.cwd() + path.sep,
    MODULE_PATH = __dirname + path.sep;

// File and directory names
const CONTENTS_JSON = 'Contents.json',
    SUCCESS_BANNER = 'banner.txt',
    HELP_BANNER = 'help.txt',
    ICON_PREFIX = 'Icon-',
    THUMBS_OUTPUT_DIR = 'AppIcon.appiconset';

// File paths
const OUTPUT_DIR_PATH = `${EXECUTION_PATH}${THUMBS_OUTPUT_DIR}${path.sep}`,
    CONTENTS_JSON_OUTPUT_PATH = `${OUTPUT_DIR_PATH}${CONTENTS_JSON}`,
    CONTENTS_JSON_PATH = `${MODULE_PATH}${CONTENTS_JSON}`,
    HELP_BANNER_PATH = MODULE_PATH + HELP_BANNER,
    SUCCESS_BANNER_PATH = MODULE_PATH + SUCCESS_BANNER,
    THUMBS_PATH = OUTPUT_DIR_PATH + ICON_PREFIX;

module.exports = {
    OUTPUT_DIR_PATH: OUTPUT_DIR_PATH,
    CONTENTS_JSON_OUTPUT_PATH: CONTENTS_JSON_OUTPUT_PATH,
    CONTENTS_JSON_PATH: CONTENTS_JSON_PATH,
    HELP_BANNER_PATH: HELP_BANNER_PATH,
    SUCCESS_BANNER_PATH: SUCCESS_BANNER_PATH,
    THUMBS_PATH: THUMBS_PATH
};