name: Time to First Review

on:
  push:
  workflow_dispatch:

jobs:
  pr-stats:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Run Time to First Review Action
        uses: ./.github/actions/time-to-first-review
        with:
          repo: "zenjob/zenjob-ios"
          github_token: ${{ github.token }}
          num_prs: 5
