name: Time to First Review

on:
  workflow_dispatch:

jobs:
  pr-stats:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Run Time to First Review Action
        uses: ./.github/actions/time-to-first-review
        with:
          repo: "leopic/makeAppIcon"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          num_prs: 100
