name: Time to First Review

on:
  workflow_dispatch:

jobs:
  pr-stats:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/iron"
      - name: Run Time to First Review Action
        uses: ./
        with:
          repo: "leopic/makeAppIcon"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          num_prs: 100
